# As the name says this is the configuration file

highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# Personal details
url: http://chaitan64arun.github.io/
baseurl: /
title: Arun Chaitanya
author: Arun Chaitanya Miriappalli
description: Personal blog
avatar: arun.jpg
email: arunmchaitanya@outlook.com
github: chaitan64arun
twitter: chaitan64arun
linkedin: arunchaitanyam
stackoverflow: users/3445161/chaitan64arun
#Comment out if you don't want disqus
disqus: arunchaitanya
google_analytics: UA-82414113-1
tel: +65 87476077
tel_full: tel:+6587476077
city: Singapore
country: Singapore


# needed for travis-ci build
exclude: [vendor]
